language: ruby
rvm: 2.2.2
cache: bundler
sudo: false

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis

deploy:
  provider: releases
  api_key:
    secure: JQmx4sGKq9eDv4r9bTQrFqNwvwjoSZT9rpDalwNzu1tjiu6sQqwsdXBZH+Zbye//k29xH14O+y5wYWZKwpy4rii4n6Er9mxWU9obMuVcg9JUIea+21BigDwv3YelcS6Fd+YvSizkp4gBwlOlGaP5kYxg39OYg3V29TlpZ6VhVSs=
  file: eve-overview-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true

env:
  - secure: aP3taS/I7SqbHFL5iccZzw4mvwA1zzggEadUupHVWSKWpu1wACf2owtUa38WwjBwiVI49O4oOvO7q0Gte9oGMB87/VahoE1DoWoLP2Q3ZpQshbCZtou6KSXimLFh6DxxMuOgBPLrrLAWRpo5WoNW3Foj3gEAMum1mHeCVFna52E=
