---
- name: ✈
  color: FFFFBB33
  overview: travel
  bracket: brackets-all

- name: pvp
  color: FFFF4444
  overview: hostile-less
  bracket: brackets-all

- name: gang
  color: FFAA66CC
  overview: extra-small_gang-less
  bracket: brackets-all

- name: drones
  color: FF99CC00
  overview: hostile-drones
  bracket: brackets-all

- name: h-tackle
  color: FFFF4444
  overview: hostile-ships-tackle
  bracket: brackets-all

- name: loot
  color: CCCCCCCC
  overview: extra-loot
  bracket: brackets-all

- name: gtfo
  color: FF33B5E5
  overview: extra-warpout
  bracket: brackets-all
